# Generated by Django 4.1 on 2022-09-11 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auNom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Non Auteur')),
                ('auPre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Prenom Auteur')),
                ('auDaNai', models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance Auteur')),
                ('auDaEm', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email Auteur')),
                ('auCon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Auteur')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification ')),
            ],
        ),
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('biNom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Non Bibliothecaire')),
                ('biPre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Prenom Bibliothecaire')),
                ('biDaEm', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email Bibliothecaire')),
                ('biDaNai', models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance Bibliothecaire')),
                ('biAdr', models.CharField(blank=True, max_length=500, null=True, verbose_name='Adresse Bibliothecaire')),
                ('biCon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Bibliothecaire')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification ')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ca', models.CharField(blank=True, max_length=150, null=True, verbose_name='Categorie')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification ')),
            ],
        ),
        migrations.CreateModel(
            name='Ecrire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification ')),
                ('ecAu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ecrire', to='adminBib.auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edNom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom de l édition')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification ')),
            ],
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viNom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Non Visiteur')),
                ('viPre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Prenom Visiteur')),
                ('daNai', models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance Visiteur')),
                ('daEm', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email Visiteur')),
                ('viAdr', models.CharField(blank=True, max_length=500, null=True, verbose_name='Adresse Visiteur')),
                ('viCon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Visiteur')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification ')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liTi', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titre')),
                ('liDe', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('liQu', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification ')),
                ('liCat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Livre', to='adminBib.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exRef', models.CharField(max_length=150)),
                ('exOp', models.CharField(choices=[('Emprunt', 'Emprunt'), ('Lecture', 'Lecture')], default='lecture', max_length=255, verbose_name='Opération')),
                ('exSt', models.CharField(choices=[('Egare', 'Egare'), ('Attente', 'Attente'), ('Retour', 'Retour'), ('Lecture', 'Lecture')], default='lecture', max_length=255, verbose_name='Statut')),
                ('exDb', models.DateField(default=django.utils.timezone.now, verbose_name='Date de debut')),
                ('exDf', models.DateField(default=django.utils.timezone.now, verbose_name='Date de fin')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification ')),
                ('exEc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exemplaire', to='adminBib.ecrire')),
                ('exEd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exemplaire', to='adminBib.edition')),
                ('exVi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Visiteur', to='adminBib.visiteur')),
            ],
        ),
        migrations.AddField(
            model_name='ecrire',
            name='ecLi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ecrire', to='adminBib.livre'),
        ),
    ]
