# Generated by Django 4.0.4 on 2022-08-09 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('daNai', models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance')),
                ('biAdr', models.CharField(blank=True, max_length=500, null=True, verbose_name='Adresse')),
                ('con', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ca', models.CharField(blank=True, max_length=150, null=True, verbose_name='Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='DonneCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Non')),
                ('prenom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Prenom')),
                ('daNai', models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance')),
                ('daEm', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edNom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom de l édition')),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('donnecommune_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminBib.donnecommune')),
                ('con', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact')),
            ],
            bases=('adminBib.donnecommune',),
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('donnecommune_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adminBib.donnecommune')),
                ('viAdr', models.CharField(blank=True, max_length=500, null=True, verbose_name='Adresse')),
                ('con', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact')),
            ],
            bases=('adminBib.donnecommune',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liTi', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titre')),
                ('liDe', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('liQu', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('liCat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Livre', to='adminBib.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exRef', models.CharField(max_length=150)),
                ('exOp', models.CharField(choices=[('Emprunt', 'Emprunt'), ('Lecture', 'Lecture')], default='lecture', max_length=255, verbose_name='Lecture/Emprunt')),
                ('exDb', models.DateField(default=django.utils.timezone.now, verbose_name='Date de debut')),
                ('exDf', models.DateField(default=django.utils.timezone.now, verbose_name='Date de fin')),
                ('exCa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exemplaire', to='adminBib.categorie')),
                ('exEd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exemplaire', to='adminBib.edition')),
                ('exLi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exemplaire', to='adminBib.livre')),
                ('exVi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Visiteur', to='adminBib.visiteur')),
            ],
        ),
        migrations.CreateModel(
            name='Ecrire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecCa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ecrire', to='adminBib.categorie')),
                ('ecLi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ecrire', to='adminBib.livre')),
                ('ecAu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ecrire', to='adminBib.auteur')),
            ],
        ),
    ]
