# Generated by Django 4.0.4 on 2022-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminBib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteur',
            name='daNai',
            field=models.CharField(max_length=150, verbose_name='Date de naissance Visiteur'),
        ),
    ]
