# Generated by Django 4.0.4 on 2022-08-15 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminBib', '0002_alter_visiteur_danai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteur',
            name='daNai',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance Visiteur'),
        ),
    ]
