# Generated by Django 4.1 on 2022-08-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminBib', '0005_alter_auteur_aucon_alter_auteur_audaem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecrire',
            name='ecCa',
        ),
    ]
