# Generated by Django 4.1 on 2022-08-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminBib', '0006_remove_ecrire_ecca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplaire',
            name='exCa',
        ),
        migrations.RemoveField(
            model_name='exemplaire',
            name='exLi',
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='exEc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exemplaire', to='adminBib.ecrire'),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='exst',
            field=models.CharField(choices=[('Egare', 'Egare'), ('Attente', 'Attente'), ('Retour', 'Retour')], default='lecture', max_length=255, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='exOp',
            field=models.CharField(choices=[('Emprunt', 'Emprunt'), ('Lecture', 'Lecture')], default='lecture', max_length=255, verbose_name='Opération'),
        ),
    ]
