# Generated by Django 4.1 on 2022-08-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminBib', '0007_remove_exemplaire_exca_remove_exemplaire_exli_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exemplaire',
            old_name='exst',
            new_name='exSt',
        ),
    ]
