# Generated by Django 4.1 on 2022-08-21 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminBib', '0009_alter_exemplaire_exst'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement'),
        ),
        migrations.AddField(
            model_name='auteur',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification '),
        ),
        migrations.AddField(
            model_name='bibliothecaire',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement'),
        ),
        migrations.AddField(
            model_name='bibliothecaire',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification '),
        ),
        migrations.AddField(
            model_name='categorie',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification '),
        ),
        migrations.AddField(
            model_name='ecrire',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement'),
        ),
        migrations.AddField(
            model_name='ecrire',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification '),
        ),
        migrations.AddField(
            model_name='edition',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement'),
        ),
        migrations.AddField(
            model_name='edition',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification '),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement'),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification '),
        ),
        migrations.AddField(
            model_name='livre',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement'),
        ),
        migrations.AddField(
            model_name='livre',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification '),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure Enregistrement'),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Heure de Modification '),
        ),
        migrations.AlterField(
            model_name='ecrire',
            name='ecAu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ecrire', to='adminBib.auteur'),
        ),
        migrations.AlterField(
            model_name='ecrire',
            name='ecLi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ecrire', to='adminBib.livre'),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='exEc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exemplaire', to='adminBib.ecrire'),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='exEd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exemplaire', to='adminBib.edition'),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='exVi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Visiteur', to='adminBib.visiteur'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='liCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Livre', to='adminBib.categorie'),
        ),
    ]
